FROM node:16.14.0

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

CMD ["npm", "run", "start"]




# FROM node:16.14.0 AS builder
# WORKDIR /app
# COPY ./package.json ./
# RUN npm install
# COPY . .

# FROM builder as test

# RUN npm run build



# CMD ["npm", "run", "start"]